# Site settings
title: Shippity, ship, ship some code
description: > # this means to ignore newlines until "baseurl:"
 Some ramblings about code, architecture, teams and other stuff. Hopefully they help someone...
 opinions are my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danofhisword.com" # the base hostname & protocol for your site
twitter_username: danofhisword

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
